/*
 AccessibilityIdentifiers
 // 作者: MiniMax Agent
 */

import Foundation

struct AccessibilityIdentifiers {
    static let mainView = "MainView"
    // static let dashboardTab = "仪表盘"
    // static let tradingTab = "交易"
    // static let portfolioTab = "投资组合"
    // static let settingsTab = "设置"
    static let tradingView = "TradingView"
    static let portfolioView = "PortfolioView"
    static let settingsView = "SettingsView"
    static let dashboardView = "DashboardView"
    // static let stockSearchField = "股票搜索"
    // static let searchResultsTable = "搜索结果"
    static let stockDetailView = "StockDetailView"
    static let currentPrice = "CurrentPrice"
    // static let buyButton = "买入"
    static let buyOrderView = "BuyOrderView"
    // static let quantityField = "数量"
    // static let orderTypeSegment = "订单类型"
    // static let marketOrderButton = "市价"
    static let estimatedAmount = "EstimatedAmount"
    // static let confirmBuyButton = "确认买入"
    // static let confirmationAlert = "确认订单"
    // static let confirmButton = "确认"
    // static let successAlert = "订单提交成功"
    // static let okButton = "确定"
    // static let sellButton = "卖出"
    static let sellOrderView = "SellOrderView"
    // static let limitOrderButton = "限价"
    // static let priceField = "限价"
    // static let confirmSellButton = "确认卖出"
    // static let positionsTable = "持仓列表"
    // static let orderHistoryButton = "订单历史"
    static let orderHistoryView = "OrderHistoryView"
    // static let ordersTable = "订单列表"
    static let symbol = "Symbol"
    static let quantity = "Quantity"
    static let price = "Price"
    static let status = "Status"
    // static let filterButton = "筛选"
    // static let pendingFilter = "未成交"
    // static let applyButton = "应用"
    // static let cancelButton = "撤销"
    // static let confirmCancelAlert = "确认撤销"
    // static let successCancelAlert = "撤销成功"
    // static let totalValueLabel = "总市值"
    // static let totalPnLLabel = "总盈亏"
    // static let dayPnLLabel = "日盈亏"
    static let positionDetailView = "PositionDetailView"
    // static let holdingQuantity = "持仓数量"
    // static let averagePrice = "平均成本"
    // static let unrealizedPnL = "浮动盈亏"
    // static let backButton = "返回"
    // static let chartTabButton = "图表"
    static let portfolioChart = "PortfolioChart"
    static let realTimePrice = "RealTimePrice"
    // static let connectionStatus = "连接状态"
    // static let notificationSection = "通知设置"
    // static let priceAlertSwitch = "价格提醒"
    // static let tradingSection = "交易设置"
    // static let defaultQuantityField = "默认数量"
    // static let saveButton = "保存"
    // static let aboutSection = "关于"
    static let aboutView = "AboutView"
    static let versionLabel = "Version"
    // static let networkErrorAlert = "网络连接错误"
    // static let validationAlert = "输入错误"
    // static let loadingIndicator = "加载中"
}